name: "EXT_INSPECTOR: Code Quality"

on:
  push:
    branches: [ "main" ]

jobs:
  inspector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HTML Lint
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          exclude: node_modules
          
      - name: JS Syntax Check
        run: |
          # Simple check to ensure JS files parses
          # Ideally use ESLint, but for now just node check
          node -c script.js
